/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.edu.clase1.cajero_automatico;

import com.unab.edu.DAO.ClsCuenta_Usuario;
import com.unab.edu.Entidades.Cuenta_Usuario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Usuario_Normal extends javax.swing.JFrame {

    /**
     * Creates new form Usuario_Normal
     */
    public Usuario_Normal() {
        initComponents();
        MostrarTabla();
        calculartotal();
        this.setLocationRelativeTo(null);
        lblIdUsuario.setVisible(false);
    }
    
    public static String fechaActual(){
        
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYYY");
        
        return formatoFecha.format(fecha);
        
    }
    
     void calculartotal(){
        
        String verificar;
        Double totalAbono = 0.0;
        Double totalCargo = 0.0;
        Double TOTALFINAL = 0.0;        
       
        for (int i = 0; i < tbCuentas.getRowCount(); i++) {
            verificar = String.valueOf(tbCuentas.getValueAt(i, 1));
            
            if(verificar.equals("Cargo")){
                
                totalCargo += Integer.parseInt(String.valueOf(tbCuentas.getValueAt(i, 0)));
                
            }
            else if(verificar.equals("Abono")){
                
                totalAbono += Integer.parseInt(String.valueOf(tbCuentas.getValueAt(i, 0)));
                
            }
//SI ES BONO SUMAR PODRAS UTILIZAR EL OPERADOR += PARA OPERAR DATOS 
//SI ES CARGO RESTAR+= PARA OPERAR DATOS 
            TOTALFINAL = totalAbono - totalCargo;
        }
        //DATO ACUMULADO PARA MOSTRAR 
        lblTotalDisponible.setText(String.valueOf(TOTALFINAL)); 
        
    }
    
    void MostrarTabla ()
    {
    
        String TITULOS[] = {"SALDO", "TRANSACCION", "FECHA"};
        DefaultTableModel ModeloTabla = new DefaultTableModel(null, TITULOS);
        ClsCuenta_Usuario clasecuentausuario = new ClsCuenta_Usuario();
        ArrayList<Cuenta_Usuario> cuenta = clasecuentausuario.MostrarCuentas();
        String filas[] = new String[5];
        for (var IterarDatos : cuenta) {

            filas[0] = String.valueOf(IterarDatos.getSaldo());

            String tipotransaccion = String.valueOf(IterarDatos.getTransaccion());
            int tipo = Integer.parseInt(tipotransaccion);

            if (tipo == 1) {
                filas[1] = "Abono";
            } else if (tipo == 2) {
                filas[1] = "Cargo";
            }
            filas[2] = String.valueOf(IterarDatos.getFecha());

            ModeloTabla.addRow(filas);

        }

        tbCuentas.setModel(ModeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCuentas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnRetirarEfectivo = new javax.swing.JButton();
        txtMonto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblTotalDisponible = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblIdUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        tbCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbCuentas);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "RETIRO DE EFECTIVO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 0, 14))); // NOI18N

        btnRetirarEfectivo.setBackground(new java.awt.Color(204, 255, 255));
        btnRetirarEfectivo.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        btnRetirarEfectivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/efectivo.png"))); // NOI18N
        btnRetirarEfectivo.setBorder(null);
        btnRetirarEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarEfectivoActionPerformed(evt);
            }
        });

        txtMonto.setBackground(new java.awt.Color(0, 0, 0));
        txtMonto.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRetirarEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnRetirarEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Saldo Disponible:");

        lblTotalDisponible.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lblTotalDisponible.setText("0");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("HISTORIAL DE MOVIMIENTOS");

        lblIdUsuario.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIdUsuario)
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(114, 114, 114))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel5)
                    .addGap(18, 18, 18)
                    .addComponent(lblTotalDisponible)
                    .addContainerGap(356, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIdUsuario)))
                .addGap(91, 91, 91)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(224, 224, 224)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(lblTotalDisponible))
                    .addContainerGap(602, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetirarEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarEfectivoActionPerformed
        
        int numero = Integer.parseInt(txtMonto.getText());
        
        if((numero%10==5)||(numero%10==0)){           
       
        
            String sDate1 = fechaActual();
            try {
                Date date1 = new SimpleDateFormat("dd/MM/YYYY").parse(sDate1);

                ClsCuenta_Usuario Cuentas = new ClsCuenta_Usuario();
                Cuenta_Usuario cuenta = new Cuenta_Usuario();
                cuenta.setSaldo(Double.parseDouble(txtMonto.getText()));
                cuenta.setTransaccion(2);
                cuenta.setFecha(date1);
                cuenta.setIdUsuario(Integer.parseInt(lblIdUsuario.getText()));
                Cuentas.AgregarTransaccion(cuenta);
                MostrarTabla();
                txtMonto.setText("");
                calculartotal();
                MostrarTabla();
        
            } catch (ParseException ex) {
                System.out.println("Error de fecha");
            }
        
             
        
            
        }
        else{
            JOptionPane.showMessageDialog(null, "El numero ingresado no es multiplo de 5");
        }
    }//GEN-LAST:event_btnRetirarEfectivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario_Normal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario_Normal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario_Normal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario_Normal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario_Normal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetirarEfectivo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblIdUsuario;
    private javax.swing.JLabel lblTotalDisponible;
    private javax.swing.JTable tbCuentas;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
